#!/usr/bin/env bash

set -euo pipefail
set -x

shopt -s extglob

REBUILD="${REBUILD:-yes}"
GIT_PUSH="${GIT_PUSH:-yes}"
DEPLOY_BRANCH="${DEPLOY_BRANCH:-master}"

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
GIT_ROOT="$(git rev-parse --show-toplevel)"
GH_PAGES_DIR="${GH_PAGES_DIR:-$GIT_ROOT/gh-pages}"

cd "${GIT_ROOT}"

git checkout "${DEPLOY_BRANCH}"
git status --porcelain
COMMIT="$(git rev-parse HEAD)"

if ! [[ "${REBUILD}" == 'no' ]]; then
    nix-shell --command 'cabal run -- site clean; cabal run -- site build'
fi

git fetch origin gh-pages

cleanup() {
    git worktree remove -- "${GH_PAGES_DIR}"
}

trap cleanup EXIT INT KILL
if ! [[ -d "${GH_PAGES_DIR}" ]]; then
    git worktree add "${GH_PAGES_DIR}" gh-pages
else
    >&2 "`${GH_PAGES_DIR}` exists! Clean it up before running."
fi

(
    cd "${GH_PAGES_DIR}"
    git checkout gh-pages
    git status --porcelain
    rm -rf -- !(CNAME)
    rsync -ah "${GIT_ROOT}/_site/" "${GH_PAGES_DIR}"
    git add *
    git commit -m "add latest files from ${COMMIT}"
    [[ "${GIT_PUSH}" == "yes" ]] && git push origin gh-pages
)
