# We MUST use the system GHC from nix-shell because 'nix: enable: true' is active below.
system-ghc: true

# This MUST exactly match the GHC version provided by your shell.nix.
# You confirmed your nix-shell provides GHC 9.6.5.
compiler: ghc-9.6.5

# Choose a single, modern LTS resolver that uses GHC 9.6.5.
# lts-22.27 is a good recent choice. (lts-22.10 and lts-22.25 also use GHC 9.6.5).
# Having duplicate 'resolver' keys is invalid; only the last one is used.
resolver: lts-22.27 # For GHC 9.6.5

packages:
  - .

extra-deps:
  # Your ndt.cabal wants hakyll >= 4.15.1.1 (or >= 4.16.0.0 if you updated it further).
  # lts-22.27 includes hakyll-4.16.6.0.
  # If your ndt.cabal allows this version (e.g., "hakyll >= 4.16.0.0"),
  # then hakyll does not need to be in extra-deps.
  # Keep this section empty unless you need packages/versions NOT in lts-22.27.

nix:
  enable: true
  # System C libraries and tools needed by Haskell packages or build process.
  # These will be sourced from your shell.nix's nixpkgs (nixos-23.11).
  # Removed duplicate 'git' and the redundant 'haskell.compiler.ghc902'.
  # 'zlib.dev' is usually just 'zlib' in nixpkgs for the necessary files.
  packages:
    - pkg-config
    - zlib
    - gmp
    - git
    - gcc
    - sass

ghc-options:
  # don't optimize locally (faster builds) and use -threaded so we don't see crashes like the following:
  #   site: file descriptor 89391920 out of range for select (0--1024).
  #   Recompile with -threaded to work around this.
  #
  "$locals": -O0 -threaded
